// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pngtjdnoyrrgtuyvomte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuZ3RqZG5veXJyZ3R1eXZvbXRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDU5NTQsImV4cCI6MjA2MjEyMTk1NH0.SAhoS0VyToRFWSOynKwKGyxT7rLcgGFm1BfMyhZCyKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);